name: CI Pipeline
on: [push]  # Runs on every push to any branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install  # Replace with your setup commands
      
      - name: Run tests
        run: npm test
